allowed-duplicate-crates = [
    "syn",
    "thiserror",
    "thiserror-impl",
    # These are all coming from eventually-postgres, quite likely sqlx...
    "hashbrown",
    "wasi",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "zerocopy",
    "zerocopy-derive",
    "getrandom",
]
